name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    env:
        GH_TOKEN: ${{ github.token }}
    steps:
    - uses: actions/checkout@v2

    - name: Setup Go environment
      uses: actions/setup-go@v2.1.4
      with:
        go-version: 1.17


    - name: Build
      run: git submodule init && git submodule sync && git submodule update --remote && cd warehouse && yarn install && yarn build

    - name: Test
      env:
        TOKEN: ${{ github.token }}
      run: echo 0
    
    - name: Deploy to Heroku
      uses: AkhileshNS/heroku-deploy@v3.12.12
      with: 
        heroku_api_key: ${{ secrets.HEROKU_API}}
        heroku_email: mo3gizaaa@gmail.com
        heroku_app_name: concourse-catalog
        
